const
  styles  = require('../lib/styles')
, { cs }  = require('./make-keyword-regex')
, rbrace  = /[()]/g
, hash    = /#/g
, number  = /-?\d+(?:\.\d+)?(?:e-?\d+)?/g
, string  = /('[^']*')|("[^"]*")/g
, comment = /;[^\n]/g
, qmark   = /\?/g
, words   = [
  'abs'
, 'acos'
, 'and'
, 'angle'
, 'append'
, 'apply'
, 'asin'
, 'assoc'
, 'assq'
, 'assv'
, 'atan'
, 'begin'
, 'bind'
, 'block'
, 'boolean'
, 'caar'
, 'cadr'
, 'call'
, 'call-with-current-continuation'
, 'call-with-input-file'
, 'call-with-output-file'
, 'call-with-values'
, 'call/cc'
, 'car'
, 'case'
, 'case-lambda'
, 'catch'
, 'cdar'
, 'cdddar'
, 'cdddd'
, 'cddddr'
, 'cddr'
, 'cdr'
, 'ceiling'
, 'char'
, 'char->integer'
, 'char-downcase'
, 'char-upcase'
, 'class'
, 'close-input-port'
, 'close-output-port'
, 'cond'
, 'cons'
, 'cos'
, 'current-input-port'
, 'current-output-port'
, 'def'
, 'define'
, 'define-class'
, 'define-syntax'
, 'delay'
, 'denominator'
, 'display'
, 'do'
, 'dynamic-wind'
, 'each'
, 'else'
, 'eq'
, 'equal'
, 'eqv'
, 'et'
, 'eval'
, 'eval-when'
, 'even'
, 'exact'
, 'exact->inexact'
, 'exit-handler'
, 'exp'
, 'expt'
, 'f'
, 'field'
, 'file'
, 'flet'
, 'floor'
, 'for'
, 'for-each'
, 'force'
, 'function'
, 'gcd'
, 'go'
, 'hash'
, 'if'
, 'imag-part'
, 'import'
, 'inexact->exact'
, 'inherit'
, 'init-field'
, 'input'
, 'integer->char'
, 'interaction-environment'
, 'interface'
, 'labels'
, 'lambda'
, 'lcm'
, 'length'
, 'let'
, 'let-syntax'
, 'let-values'
, 'let/ec'
, 'letrec'
, 'letrec-syntax'
, 'list'
, 'list->string'
, 'list->vector'
, 'list-ref'
, 'list-tail'
, 'load'
, 'load-time-values'
, 'locally'
, 'log'
, 'macrolet'
, 'magnitude'
, 'make-polar'
, 'make-rectangular'
, 'make-string'
, 'make-vector'
, 'map'
, 'max'
, 'member'
, 'memq'
, 'memv'
, 'min'
, 'mixin'
, 'modulo'
, 'multiple-value-call'
, 'multiple-value-prog1'
, 'names'
, 'negative'
, 'newline'
, 'not'
, 'null'
, 'null-environment'
, 'number'
, 'number->string'
, 'numerator'
, 'odd'
, 'open'
, 'open-input-file'
, 'open-output-file'
, 'opt-lambda'
, 'or'
, 'output'
, 'override'
, 'pair'
, 'peek-char'
, 'port'
, 'prog'
, 'progn'
, 'progv'
, 'protect'
, 'provide'
, 'public'
, 'quasiquote'
, 'quote'
, 'quotient'
, 'rationalize'
, 'read'
, 'read-char'
, 'real'
, 'real-part'
, 'ref'
, 'remainder'
, 'rename'
, 'require'
, 'require-for-syntax'
, 'return-from'
, 'reverse'
, 'round'
, 'rules'
, 'scheme-report-environment'
, 'set'
, 'setq'
, 'sin'
, 'sqrt'
, 'string'
, 'string->list'
, 'string->number'
, 'string->symbol'
, 'string-append'
, 'string-copy'
, 'string-length'
, 'string-ref'
, 'substring'
, 'symbol->string'
, 'symbol-macrolet'
, 'syntax'
, 'syntax-case'
, 'syntax-error'
, 'syntax-rules'
, 't'
, 'tagbody'
, 'tail'
, 'tan'
, 'the'
, 'throw'
, 'transcript-off'
, 'transcript-on'
, 'truncate'
, 'unit'
, 'unit/sig'
, 'unless'
, 'unwind-protect'
, 'values'
, 'vector'
, 'vector->list'
, 'vector-length'
, 'vector-ref'
, 'when'
, 'with'
, 'with-input-from-file'
, 'with-output-to-file'
, 'with-syntax'
, 'write'
, 'write-char'
, 'λ'
]
, keyword = cs(words)

exports.highlight = q => {
  q.wrap(rbrace  , styles.brightYellow)
  q.wrap(qmark   , styles.brightCyan)
  q.wrap(hash    , styles.brightCyan)
  q.wrap(number  , styles.brightMagenta)
  q.wrap(keyword , styles.brightBlue)
  q.wrap(comment , styles.grey)
  q.wrap(string  , styles.red)
}

exports.test = file => /\.(scm|ss|el|elc|lisp|lsp|l|cl|fasl|rkt)$/.test(file)
